services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: goodhamburger-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "${SQL_PASSWORD:-GoodHamburger@12345}"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql

  api:
    build:
      context: .
      dockerfile: src/GoodHamburger.Api/Dockerfile
    container_name: goodhamburger-api
    depends_on:
      - sqlserver
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://+:8080"
      App__UseHttpsRedirection: "false"
      ConnectionStrings__Default: "Server=sqlserver,1433;Database=GoodHamburgerDb;User Id=sa;Password=${SQL_PASSWORD:-GoodHamburger@12345};TrustServerCertificate=True"
      Jwt__SecretKey: "${JWT_SECRET_KEY:?JWT_SECRET_KEY must be configured}"
      Jwt__Issuer: "GoodHamburger.Api"
      Jwt__Audience: "GoodHamburger.User"
      Jwt__ExpiresInMinutes: "60"
    ports:
      - "18080:8080"

  web:
    build:
      context: .
      dockerfile: src/GoodHamburger.Web/Dockerfile
    container_name: goodhamburger-web
    depends_on:
      - api
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://+:8080"
      Api__BaseUrl: "http://api:8080"
    ports:
      - "18081:8080"

volumes:
  sqlserver-data:
